apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: mediawiki
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mediawiki-sc
  resources:
    requests:
      storage: 4Gi

