kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  namespace: "mediawiki"
  name: mediawiki-sc
  labels:
    {{- include "storage.labels" . | nindent 4 }}
provisioner: disk.csi.azure.com
volumeBindingMode: WaitForFirstConsumer
